# Generated by Django 5.2.8 on 2026-06-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order_courier_name_order_estimated_delivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
